
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 46
#define YY_END_OF_BUFFER 47
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[363] =
    {   0,
        0,    0,    0,    0,    0,    0,   47,   45,   43,   44,
       45,   24,   29,   41,   40,   16,   18,    9,   15,   31,
       39,   39,   39,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,    2,    5,    6,    5,    7,    8,
        4,   43,    0,    1,    0,    9,    0,   13,   39,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   17,   42,   17,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       23,   42,   12,   42,   12,   42,   42,   42,   42,   42,

       42,   42,   42,   42,   12,   42,   38,   42,   42,   38,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   12,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,    3,   11,    0,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   41,   42,   42,   42,   20,
       20,   42,   42,   12,   12,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   41,   25,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   34,   35,
       35,   42,   42,   42,   10,   42,   42,   42,   42,   42,

       42,   42,   42,   42,   19,   19,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   32,   32,   42,   42,   42,   42,   14,
       14,   12,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   33,   36,   36,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   26,   42,   42,   42,   42,

       42,   42,   30,   42,   42,   42,   42,   42,   21,   21,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   28,   28,   42,   42,   37,   37,   42,   42,   22,
       22,   42,    0,   42,   42,   42,   42,   27,   27,   42,
       42,   42,   42,   42,   42,   42,   42,    0,   42,   42,
       42,   42,   42,    0,   42,   42,    0,   42,   42,    0,
       12,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    4,    5,
        6,    7,    8,    9,    8,   10,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   14,   15,
       16,   17,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   34,
       43,    1,    1,    1,    1,    1,   18,   44,   20,   45,

       46,   23,   24,   25,   26,   27,   28,   29,   47,   48,
       49,   33,   34,   50,   36,   37,   51,   39,   52,   41,
       42,   34,   53,    1,   54,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[55] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[367] =
    {   0,
        0,    0,   52,   53,   54,   55,  191, 1276,  169, 1276,
        0,  153, 1276, 1276, 1276, 1276, 1276,   51,  140, 1276,
       48, 1276,  139,   92,  128,   44,   45,   57,  135,   46,
       50,  157,  131,   53,  136,  187,  148,   58,  170,  186,
      193,  147,  201,  168, 1276, 1276, 1276,  148, 1276, 1276,
     1276,  150,  147, 1276,  102,  209,  127, 1276, 1276,   60,
      153,  221,  218,  224,  212,   61,  228,  230,    0,  235,
      238,  239,  241,  247,  255,  260,  257,  264,  268,  266,
      283,  272,  294,  295,  297,  300,  299,  304,  305,  316,
      261,  311,  334,  332,  339,  347,  351,  353,  348,  338,

      355,  364,  365,  368,  291,  333,  336,  381,  385,  359,
      384,  393,  387,  400,  415,  418,  423,  428,  412,  443,
      407,  433,  437,  445,  446,  451,  464,  459,  465,  472,
      474,  473,  481, 1276, 1276,   88,  490,  491,  499,  502,
      479,  504,  507,  510,  508,  511,  513,  520,  512,  516,
      524,  527,  530,  538,  541,  545,  549,  550,  557,  552,
      563,  555,  558,  561,  566,  570,  572,  575,  578,  584,
      580,  593,  601,  607,  612,  611,  613,  592,  618,  620,
      623,  632,  640,  626,  628,  629,  645,  646,  630,  648,
      651,  655,  665,  661,   77,  667,  671,  657,  673,  683,

      680,  686,  687,  688,  690,  692,  705,  719,  694,  700,
      717,  720,  723,  722,  727,  752,  753,  738,  739,  758,
      761,  764,  742,  765,  767,  768,  770,  771,  786,  787,
      779,  804,  797,  805,  807,  808,  809,  812,  814,  813,
      816,  822,  818,  825,  839,  844,  845,  851,  852,  857,
      859,  862,  870,  824,  861,  877,  887,  880,  890,  891,
      892,  897,  899,  889,  910,  909,  918,  929,  930,  928,
      936,  937,  931,  938,  943,  939,  944,  947,  949,  957,
      969,  970,  958,  972,  978,  979,  966,  992,  998,  999,
      980,  983,  995, 1012, 1014,  989, 1005, 1011, 1018, 1025,

     1043, 1044, 1006, 1037, 1028, 1057, 1058, 1045, 1048, 1051,
     1064, 1065, 1077, 1078, 1059, 1096, 1084, 1100, 1105, 1106,
     1114, 1085, 1107, 1116, 1122, 1111, 1117, 1132, 1126, 1125,
     1137, 1148,   63, 1155, 1158, 1160, 1143, 1152, 1154, 1162,
     1163, 1164, 1173, 1185, 1177, 1191, 1192,   37, 1170, 1198,
     1200, 1208, 1199,   47, 1206, 1210,   38, 1217, 1218,   53,
     1276, 1276, 1266, 1269, 1272,   66
    } ;

static yyconst flex_int16_t yy_def[367] =
    {   0,
      362,    1,  363,  363,  364,  364,  362,  362,  362,  362,
      365,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,   24,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,   25,
       25,   25,   25,   25,   25,   25,   25,   25,  366,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,

       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,  362,  362,  362,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,  362,   25,   25,   25,   25,   25,

       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,

       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,  362,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,  362,   25,   25,
       25,   25,   25,  362,   25,   25,  362,   25,   25,  362,
      362,    0,  362,  362,  362,  362
    } ;

static yyconst flex_int16_t yy_nxt[1331] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       14,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   31,   31,   33,   34,
       35,   36,   37,   31,   38,   39,   40,   41,   42,   43,
       44,   31,    8,   25,   27,   28,   34,   35,   36,   38,
       41,   43,   45,    8,   47,   47,   50,   50,   48,   48,
       55,   72,   56,   59,   59,   60,   75,   60,   69,  360,
       76,   60,  357,  354,   60,   73,   77,   89,   60,  115,
      348,   60,   60,  361,   97,   80,  360,   81,  195,   66,
       78,   66,   74,   79,   90,   66,   57,   82,   66,  195,

      361,   98,   66,  116,   83,   66,   66,   51,   51,   60,
       61,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   62,   60,   60,   60,   63,   64,   60,   60,
       60,   60,   60,   60,  136,   65,   66,   66,   66,   67,
       66,   68,   66,   66,   69,   69,   60,   57,   96,   70,
      135,   52,   60,  134,   59,   58,   60,   99,   60,   54,
       84,  100,   60,   60,  127,  112,   85,  101,   60,   60,
       52,   66,   86,   71,   60,   66,   66,   66,   60,   91,
       66,  102,  113,   87,  103,   88,   92,   93,  137,   60,
      362,  117,   66,   66,  118,  362,  362,  114,   66,  132,

      362,  362,   66,   94,   95,  104,  119,   60,   60,  105,
      121,  362,  362,   66,   60,  120,  133,  105,   55,  106,
       56,  107,   60,  124,  108,  128,  129,  122,  125,  362,
      109,   66,   66,   60,  123,  130,  110,  111,   66,   60,
      126,  107,   60,  362,  362,   60,   66,  137,  107,   60,
      131,   60,  138,  105,   57,  362,   60,   66,  140,   60,
       60,  140,   60,   66,  138,  110,   66,  139,   60,   66,
      123,  142,  110,   66,  141,   66,   60,  142,   60,  139,
       66,   60,   60,   66,   66,   60,   66,   60,  143,   60,
      144,  362,   66,   60,  143,  145,  147,  152,  146,  144,

       66,  149,   66,  150,   60,   66,   66,  147,  148,   66,
      362,   66,   60,   66,  150,   60,   60,   66,   60,  148,
       60,   60,  362,  153,  362,   60,   60,  151,   66,  362,
      156,  154,   60,  154,  156,  362,   66,   60,  151,   66,
       66,  158,   66,  159,   66,   66,  155,  157,  155,   66,
       66,  157,  158,   60,  168,   60,   66,   60,  160,   60,
       60,   66,  161,  160,  159,  163,  105,  161,   60,   60,
      162,  146,   60,  146,   60,  162,   60,   66,  169,   66,
       60,   66,  362,   66,   66,   60,   60,  105,  362,   60,
      164,  166,   66,   66,  167,  165,   66,  165,   66,  123,

       66,  166,   60,  105,   66,   60,   60,  362,   60,   66,
       66,  167,  171,   66,   60,  123,  362,  170,  174,  362,
      170,   60,  362,  362,  362,  362,   66,  172,  182,   66,
       66,  174,   66,   60,  176,  175,   60,  176,   66,   60,
      177,  362,  173,  177,   60,   66,  180,  178,  175,   60,
      178,  179,  183,  362,   60,  362,  105,   66,   60,  105,
       66,  181,  105,   66,   60,  184,   60,  187,   66,  362,
      185,  179,   60,   66,  362,  362,  185,  123,   66,  105,
       60,  186,   66,  362,  192,   60,   60,  186,   66,  362,
       66,  188,  189,   60,   60,   60,   66,  194,  190,  194,

      105,  193,   60,  362,   66,  362,  362,  105,  198,   66,
       66,   60,   60,  191,  362,  105,  198,   66,   66,   66,
       60,  196,  123,   60,  123,   60,   66,  199,   60,   60,
      123,   60,   60,  205,   60,   66,   66,   60,  197,  200,
      202,   60,  200,  203,   66,   60,  201,   66,   60,   66,
      203,  105,   66,   66,  362,   66,   66,  206,   66,   60,
      204,   66,   60,  105,  209,   66,   60,  204,  209,   66,
       60,   60,   66,  211,  362,  123,  214,  207,   60,  216,
      207,  105,  216,   66,   60,  210,   66,   60,  213,  208,
       66,   60,  208,  218,   66,   66,   60,  212,  123,   60,

      215,   60,   66,  217,  362,   60,  217,  223,   66,  220,
      224,   66,  220,  231,   60,   66,  222,  219,  224,  362,
       66,  362,   60,   66,  221,   66,  225,  221,   60,   66,
      226,  225,   60,   60,   60,  226,  362,  232,   66,   60,
      105,   60,  227,  229,   60,  233,   66,  105,  233,   60,
       60,   60,   66,   60,  236,  362,   66,   66,   66,  228,
      230,   60,  234,   66,  105,   66,   60,   60,   66,   60,
      234,  123,   60,   66,   66,   66,   60,   66,   60,  235,
      105,  105,   60,  237,  362,   66,   60,  235,   60,  105,
       66,   66,   60,   66,   60,  239,   66,  238,  105,  239,

       66,   60,   66,  240,   60,  362,   66,   60,   60,   60,
       66,   60,   66,   60,  243,   60,   66,  245,   66,  242,
      241,  250,  248,  247,  247,   66,   60,  362,   66,  244,
      249,   66,   66,   66,  246,   66,  248,   66,   60,   66,
       60,   60,  362,   60,   60,  251,  362,  362,   60,  362,
       66,  252,  362,  254,  252,  362,  256,  258,  258,   60,
       60,  256,   66,  262,   66,   66,  253,   66,   66,  253,
      255,  257,   66,   60,   60,  259,  257,  362,  259,   60,
      105,  105,   60,   66,   66,   60,   60,  263,  266,   60,
      362,   60,   60,  362,  264,  362,  273,   66,   66,  362,

       60,  260,  268,   66,  270,  270,   66,   60,   60,   66,
       66,  265,  267,   66,  261,   66,   66,  269,   60,  271,
      271,  273,  272,  272,   66,   60,   60,  274,   60,   60,
      277,   66,   66,  279,   60,   60,  276,   60,  362,   60,
      362,  362,   66,   60,  275,  105,   60,  362,  362,   66,
       66,  281,   66,   66,  278,  285,  283,  280,   66,   66,
       60,   66,  285,   66,  282,   60,   60,   66,  286,  123,
       66,  284,   60,   60,  287,  286,  105,  290,   60,  287,
       60,  362,  105,   60,   66,  288,  291,  293,  291,   66,
       66,   60,  362,  123,  362,  293,   66,   66,   60,  294,

      289,   60,   66,  292,   66,  292,  123,   66,   60,  294,
       60,   60,   60,   60,  362,   66,  105,  105,   60,  105,
       60,  362,   66,  362,  297,   66,  295,  296,  296,  298,
       60,   60,   66,  362,   66,   66,   66,   66,  298,   60,
      362,  123,   66,  123,   66,  297,  300,  300,  105,   60,
       60,   60,   60,  299,   66,   66,  105,   60,   60,   60,
       60,  105,  299,   66,   60,   60,  105,  303,   60,  362,
       60,  301,  123,   66,   66,   66,   66,  304,   60,   60,
      123,   66,   66,   66,   66,  304,  302,  105,   66,   66,
       60,   60,   66,   60,   66,  306,  362,  308,  308,   60,

       60,  313,   66,   66,  313,  305,  305,  362,  307,  306,
       60,  123,  309,   60,   66,   66,   60,   66,  309,   60,
       60,  362,  307,   66,   66,  314,   60,   60,  314,  316,
      311,  315,   60,   60,   66,   60,  310,   66,  362,   60,
       66,  319,  310,   66,   66,  317,   60,  312,  320,  105,
       66,   66,  362,  362,  322,  320,   66,   66,   60,   66,
      362,  321,  318,   66,   60,   60,   60,  326,  321,   60,
       66,  323,   60,  123,  324,  324,  328,  328,   60,   60,
      335,  329,   66,  362,  327,   60,   60,  362,   66,   66,
       66,  325,  325,   66,  330,  330,   66,  362,   60,   60,

      362,  362,   66,   66,  336,   60,   60,  332,  332,   66,
       66,  331,  331,  332,  332,  337,  362,   60,  105,  333,
      333,   60,   66,   66,  334,  334,   60,   60,   60,   66,
       66,  362,   60,  123,  105,   60,  342,   60,   60,  338,
      340,   66,  342,   60,  362,   66,   60,   60,  340,  123,
       66,   66,   66,   60,  339,  341,   66,  345,   60,   66,
      343,   66,   66,  341,  105,  347,  343,   66,  344,   60,
       66,   66,  347,   60,  346,   60,   60,   66,  105,   60,
      105,   60,   66,  105,  105,   60,  362,  362,  123,  355,
      362,   60,  362,   66,   60,  362,  362,   66,   60,   66,

       66,  349,  123,   66,  123,   66,   60,  123,  123,   66,
      349,  105,   60,   60,  350,   66,  351,  355,   66,   60,
       60,   60,   66,  350,  356,  105,  123,  105,  353,   60,
       66,   60,  362,  352,  105,  362,   66,   66,   60,   60,
      123,  358,  105,   66,   66,   66,  362,  105,  105,  123,
      362,  123,  362,   66,  362,   66,  362,  123,  359,  362,
      362,  362,   66,   66,  123,  123,   46,   46,   46,   49,
       49,   49,   53,  362,   53,    7,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362
    } ;

static yyconst flex_int16_t yy_chk[1331] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    5,    6,    3,    4,
       18,   26,   18,   21,   21,   26,   27,   30,  366,  357,
       27,   31,  354,  348,   34,   26,   27,   30,   28,   38,
      333,   60,   66,  360,   34,   28,  357,   28,  195,   26,
       27,   30,   26,   27,   30,   31,   18,   28,   34,  136,

      360,   34,   28,   38,   28,   60,   66,    5,    6,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   57,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   25,   55,   33,   25,
       53,   52,   33,   48,   23,   19,   29,   35,   25,   12,
       29,   35,   25,   25,   42,   37,   29,   35,   42,   37,
        9,   25,   29,   25,   61,   25,   33,   25,   32,   32,
       29,   35,   37,   29,   35,   29,   32,   32,   61,   44,
        7,   39,   42,   37,   39,    0,    0,   37,   61,   44,

        0,    0,   32,   32,   32,   36,   39,   40,   36,   36,
       40,    0,    0,   44,   41,   39,   44,   40,   56,   36,
       56,   36,   43,   41,   36,   43,   43,   40,   41,    0,
       36,   40,   36,   65,   40,   43,   36,   36,   41,   63,
       41,   62,   62,    0,    0,   64,   43,   65,   67,   67,
       43,   68,   63,   64,   56,    0,   70,   65,   70,   71,
       72,   71,   73,   63,   68,   62,   62,   63,   74,   64,
       64,   73,   67,   67,   72,   68,   75,   74,   77,   68,
       70,   76,   91,   71,   72,   78,   73,   80,   73,   79,
       75,    0,   74,   82,   74,   76,   77,   82,   76,   78,

       75,   80,   77,   81,   81,   76,   91,   79,   77,   78,
        0,   80,  105,   79,   83,   83,   84,   82,   85,   79,
       87,   86,    0,   84,    0,   88,   89,   81,   81,    0,
       86,   85,   92,   87,   88,    0,  105,   90,   83,   83,
       84,   89,   85,   92,   87,   86,   85,   86,   87,   88,
       89,   88,   90,   94,  106,   93,   92,  107,   93,  100,
       95,   90,   93,   95,   94,   96,  100,   95,   96,   99,
       93,   97,   97,   98,   98,   95,  101,   94,  106,   93,
      110,  107,    0,  100,   95,  102,  103,   99,    0,  104,
       96,  101,   96,   99,  104,   97,   97,   98,   98,   99,

      101,  103,  108,  102,  110,  111,  109,    0,  113,  102,
      103,  109,  112,  104,  112,  102,    0,  108,  113,    0,
      111,  114,    0,    0,    0,    0,  108,  112,  121,  111,
      109,  114,  113,  119,  115,  113,  115,  116,  112,  116,
      115,    0,  112,  116,  117,  114,  119,  115,  114,  118,
      116,  117,  121,    0,  122,    0,  118,  119,  123,  117,
      115,  119,  118,  116,  120,  122,  124,  125,  117,    0,
      124,  120,  126,  118,    0,    0,  126,  118,  122,  120,
      128,  124,  123,    0,  128,  127,  129,  126,  120,    0,
      124,  125,  127,  130,  132,  131,  126,  130,  127,  131,

      141,  129,  133,    0,  128,    0,    0,  132,  138,  127,
      129,  137,  138,  127,    0,  133,  139,  130,  132,  131,
      139,  137,  132,  140,  141,  142,  133,  140,  143,  145,
      133,  144,  146,  149,  147,  137,  138,  150,  137,  142,
      145,  148,  143,  147,  139,  151,  144,  140,  152,  142,
      148,  153,  143,  145,    0,  144,  146,  149,  147,  154,
      147,  150,  155,  152,  156,  148,  156,  148,  157,  151,
      157,  158,  152,  160,    0,  153,  162,  154,  159,  163,
      155,  158,  164,  154,  161,  159,  155,  165,  161,  154,
      156,  166,  155,  167,  157,  158,  168,  160,  158,  169,

      162,  171,  159,  163,    0,  170,  164,  171,  161,  168,
      172,  165,  169,  178,  172,  166,  170,  167,  173,    0,
      168,    0,  173,  169,  168,  171,  174,  169,  174,  170,
      174,  175,  176,  175,  177,  175,    0,  178,  172,  179,
      179,  180,  176,  177,  181,  180,  173,  184,  181,  185,
      186,  189,  174,  182,  186,    0,  176,  175,  177,  176,
      177,  183,  182,  179,  185,  180,  187,  188,  181,  190,
      183,  184,  191,  185,  186,  189,  192,  182,  198,  182,
      187,  188,  194,  192,    0,  183,  193,  183,  196,  193,
      187,  188,  197,  190,  199,  196,  191,  194,  198,  197,

      192,  201,  198,  199,  200,    0,  194,  202,  203,  204,
      193,  205,  196,  206,  201,  209,  197,  202,  199,  200,
      199,  210,  207,  203,  204,  201,  207,    0,  200,  201,
      209,  202,  203,  204,  202,  205,  208,  206,  211,  209,
      208,  212,    0,  214,  213,  210,    0,    0,  215,    0,
      207,  211,    0,  213,  212,    0,  214,  218,  219,  218,
      219,  215,  211,  223,  208,  212,  211,  214,  213,  212,
      213,  214,  215,  216,  217,  220,  215,    0,  221,  220,
      216,  217,  221,  218,  219,  222,  224,  223,  225,  226,
        0,  227,  228,    0,  224,    0,  231,  216,  217,    0,

      231,  222,  226,  220,  227,  228,  221,  229,  230,  222,
      224,  224,  225,  226,  222,  227,  228,  226,  233,  227,
      228,  232,  229,  230,  231,  232,  234,  233,  235,  236,
      237,  229,  230,  238,  240,  239,  236,  241,    0,  243,
        0,    0,  233,  242,  233,  254,  244,    0,    0,  232,
      234,  239,  235,  236,  237,  243,  242,  238,  240,  239,
      245,  241,  244,  243,  239,  246,  247,  242,  243,  254,
      244,  242,  248,  249,  245,  244,  247,  249,  250,  246,
      251,    0,  255,  252,  245,  248,  250,  252,  251,  246,
      247,  253,    0,  247,    0,  253,  248,  249,  256,  256,

      248,  258,  250,  250,  251,  251,  255,  252,  257,  257,
      264,  259,  260,  261,    0,  253,  258,  262,  262,  263,
      263,    0,  256,    0,  264,  258,  259,  260,  261,  266,
      266,  265,  257,    0,  264,  259,  260,  261,  267,  267,
        0,  262,  262,  263,  263,  265,  268,  269,  270,  270,
      268,  269,  273,  266,  266,  265,  271,  271,  272,  274,
      276,  274,  267,  267,  275,  277,  275,  273,  278,    0,
      279,  272,  270,  270,  268,  269,  273,  279,  280,  283,
      271,  271,  272,  274,  276,  280,  272,  287,  275,  277,
      281,  282,  278,  284,  279,  283,    0,  285,  286,  285,

      286,  291,  280,  283,  292,  281,  282,    0,  283,  284,
      296,  287,  288,  288,  281,  282,  293,  284,  289,  289,
      290,    0,  284,  285,  286,  291,  297,  303,  292,  294,
      290,  293,  298,  294,  296,  295,  288,  288,    0,  299,
      293,  297,  289,  289,  290,  295,  300,  290,  298,  305,
      297,  303,    0,    0,  300,  299,  298,  294,  304,  295,
        0,  298,  295,  299,  301,  302,  308,  304,  299,  309,
      300,  300,  310,  305,  301,  302,  306,  307,  306,  307,
      315,  308,  304,    0,  304,  311,  312,    0,  301,  302,
      308,  301,  302,  309,  311,  312,  310,    0,  313,  314,

        0,    0,  306,  307,  315,  317,  322,  313,  314,  311,
      312,  311,  312,  313,  314,  316,    0,  316,  317,  313,
      314,  318,  313,  314,  313,  314,  319,  320,  323,  317,
      322,    0,  326,  317,  318,  321,  324,  324,  327,  319,
      320,  316,  325,  325,    0,  318,  330,  329,  321,  318,
      319,  320,  323,  328,  319,  320,  326,  329,  331,  321,
      324,  324,  327,  321,  337,  332,  325,  325,  328,  332,
      330,  329,  334,  338,  329,  339,  334,  328,  335,  335,
      336,  336,  331,  340,  341,  342,    0,    0,  337,  349,
        0,  349,    0,  332,  343,    0,    0,  338,  345,  339,

      334,  342,  335,  335,  336,  336,  344,  340,  341,  342,
      343,  345,  346,  347,  342,  349,  344,  350,  343,  350,
      353,  351,  345,  343,  353,  346,  345,  355,  347,  352,
      344,  356,    0,  344,  351,    0,  346,  347,  358,  359,
      346,  356,  352,  350,  353,  351,    0,  358,  359,  351,
        0,  355,    0,  352,    0,  356,    0,  352,  356,    0,
        0,    0,  358,  359,  358,  359,  363,  363,  363,  364,
      364,  364,  365,    0,  365,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "mpascanner.l"
#line 2 "mpascanner.l"

#include <stdio.h>
#include <stdlib.h>

int line = 1;
int col = 1;


#line 871 "lex.yy.c"

#define INITIAL 0
#define BRACECOMMENT 1
#define CURLYCOMMENT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 106 "mpascanner.l"



#line 1059 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 363 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1276 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 109 "mpascanner.l"
;	{BEGIN BRACECOMMENT;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 110 "mpascanner.l"
;	{BEGIN CURLYCOMMENT;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 112 "mpascanner.l"
;	{BEGIN 0; col=col+yyleng;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 113 "mpascanner.l"
;	{BEGIN 0; col=col+yyleng;}
	YY_BREAK
case YY_STATE_EOF(BRACECOMMENT):
#line 115 "mpascanner.l"
;	{col+=yyleng; printf("Line %d, col %d: unterminated comment\n", line, col); BEGIN 0;}
	YY_BREAK
case YY_STATE_EOF(CURLYCOMMENT):
#line 116 "mpascanner.l"
;	{col+=yyleng; printf("Line %d, col %d: unterminated comment\n", line, col); BEGIN 0;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 118 "mpascanner.l"
;	{col=col+yyleng;}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 119 "mpascanner.l"
;	{line++; col=1;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 121 "mpascanner.l"
;	{col=col+yyleng;}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 122 "mpascanner.l"
;	{line++; col=1;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 125 "mpascanner.l"
; 	{printf("INTLIT(%s)\n", yytext); col=col+yyleng;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 126 "mpascanner.l"
; 	{printf("REALLIT(%s)\n", yytext); col=col+yyleng;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 127 "mpascanner.l"
; 	{printf("STRING(%s)\n", yytext); col=col+yyleng;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 129 "mpascanner.l"
;	{printf("RESERVED(%s)\n", yytext); col=col+yyleng;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 131 "mpascanner.l"
; 	{printf("ASSIGN\n"); col=col+yyleng;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 132 "mpascanner.l"
; 	{printf("BEGIN\n"); col=col+yyleng;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 133 "mpascanner.l"
; 	{printf("COLON\n"); col=col+yyleng;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 134 "mpascanner.l"
; 	{printf("COMMA\n"); col=col+yyleng;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 135 "mpascanner.l"
; 	{printf("DO\n\n"); col=col+yyleng;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 136 "mpascanner.l"
; 	{printf("DOT\n"); col=col+yyleng;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 137 "mpascanner.l"
; 	{printf("ELSE\n"); col=col+yyleng;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 138 "mpascanner.l"
; 	{printf("END\n"); col=col+yyleng;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 139 "mpascanner.l"
; 	{printf("FORWARD\n"); col=col+yyleng;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 140 "mpascanner.l"
; 	{printf("FUNCTION\n"); col=col+yyleng;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 141 "mpascanner.l"
; 	{printf("IF\n"); col=col+yyleng;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 142 "mpascanner.l"
; 	{printf("LBRAC\n"); col=col+yyleng;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 143 "mpascanner.l"
; 	{printf("NOT\n"); col=col+yyleng;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 144 "mpascanner.l"
; 	{printf("OUTPUT\n"); col=col+yyleng;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 145 "mpascanner.l"
; 	{printf("PARAMSTR\n"); col=col+yyleng;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 146 "mpascanner.l"
; 	{printf("PROGRAM\n"); col=col+yyleng;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 147 "mpascanner.l"
; 	{printf("RBRAC\n"); col=col+yyleng;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 148 "mpascanner.l"
; 	{printf("REPEAT\n"); col=col+yyleng;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 149 "mpascanner.l"
; 	{printf("SEMIC\n"); col=col+yyleng;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 150 "mpascanner.l"
; 	{printf("THEN\n"); col=col+yyleng;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 151 "mpascanner.l"
; 	{printf("UNTIL\n"); col=col+yyleng;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 152 "mpascanner.l"
; 	{printf("VAL\n"); col=col+yyleng;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 153 "mpascanner.l"
; 	{printf("VAR\n"); col=col+yyleng;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 154 "mpascanner.l"
; 	{printf("WHILE\n"); col=col+yyleng;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 155 "mpascanner.l"
; 	{printf("WRITELN\n"); col=col+yyleng;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 157 "mpascanner.l"
; 	{printf("OP1(%s)\n", yytext); col=col+yyleng;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 158 "mpascanner.l"
; 	{printf("OP2(%s)\n", yytext); col=col+yyleng;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 159 "mpascanner.l"
; 	{printf("OP3(%s)\n", yytext); col=col+yyleng;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 160 "mpascanner.l"
; 	{printf("OP4(%s)\n", yytext); col=col+yyleng;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 162 "mpascanner.l"
; 	{printf("ID(%s)\n", yytext);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 164 "mpascanner.l"
;	{col=col+yyleng;}
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 165 "mpascanner.l"
; 	{line++; col=1;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 167 "mpascanner.l"
; 	{col=col+yyleng; printf("Line %d, col %d: illegal character (\'%c\')\n", line, col, yytext[0]);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 170 "mpascanner.l"
ECHO;
	YY_BREAK
#line 1383 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 363 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 363 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 362);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 170 "mpascanner.l"



int main(){
	yylex();
	return 0;
}

int yywrap(){
	return 1;
}

